name: Snyk Scan

on:
  push: { }
  pull_request_target:
    types: [ opened ]

jobs:
  snyk:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["jupierce", "sosiouxme", "thiagoalessio", "joepvd", "thegreyd", "vfreex", "locriandev", "Ximinhan", "ashwindasr"]'), github.actor)
    steps:
      - uses: actions/checkout@v3
      - name: Test for open source vulnerabilities and license issues.
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --all-projects
      - name: Test for any known security issues using Static Code Analysis.
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --all-projects
